### PR TITLE
Fix Jacksonized stops generating JsonProperty/JsonIgnore after first manual annotation (fluent=true)

### LINKED ISSUE #4022: [BUG]  Jacksonized stops generating JsonProperty after first manual annotation (fluent=true)
**Describe the bug**
`@Jacksonized` stops generating `@JsonProperty` annotations once a property with existing `@JsonProperty` annotation is encountered, when using `@Accessors(fluent = true)` with Jackson 3.

**To Reproduce**

With the configuration `lombok.jacksonized.jacksonVersion += 3`,  the following code:

```Java
@Jacksonized
@Builder
@Getter
@Accessors(fluent = true)
public class Example {

    private String a;
    @JsonProperty("B")
    private String b;
    private String c;
}
```
generates:

```Java
@JsonDeserialize(
    builder = ExampleBuilder.class
)
public class Example {
    @JsonProperty("a")
    private String a;
    @JsonProperty("B")
    private String b;
    private String c;

   //....
}
```

**Expected behavior**
`private String c;` annotated with `@JsonProperty("c")`

**Version info (please complete the following information):**
 - Lombok version: `1.18.44`
 - Jackson version: `3.1.0`

**Additional context**
Github repository with the example

https://github.com/ralemanc/lombok_bug_Jacksonized_JsonProperty/tree/main

**Possible fix**
https://github.com/ralemanc/lombok/commit/cc025dc49e8fe94b67ec037341cb24aa3dad4795

### PR DESCRIPTION
**Pull request by ralemanc**
This PR fixes #4022

### CODE REVIEW

File: src/core/lombok/javac/handlers/HandleJacksonized.java [hunk 1]
```diff
@@ -116,14 +116,13 @@ private void handleJacksonizedAccessors(JavacNode annotationNode, JavacNode anno
...
-					createJsonIgnoreForField(javacNode, annotationNode);
-				} else {
-					createJsonPropertyForField(javacNode, annotationNode);
+				if (!hasAnnotation(javacNode, JacksonAnnotationType.JSON_PROPERTY2) &&
+					!hasAnnotation(javacNode, JacksonAnnotationType.JSON_IGNORE2)) {
+					if (javacNode.isTransient()) {
+						createJsonIgnoreForField(javacNode, annotationNode);
+					} else {
+						createJsonPropertyForField(javacNode, annotationNode);
+					}
```
Comment (nealeu) [inline src/core/lombok/javac/handlers/HandleJacksonized.java]: I think `return` -> `continue` would have bean more readable.

However, even with that, is this really the intent.

To match what the comments above say, then this would make sense
```java
	if (javacNode.isTransient()) {
		if (!hasAnnotation(javacNode, JacksonAnnotationType.JSON_IGNORE2)) {
			createJsonIgnoreForField(javacNode, annotationNode);
		}
	} else if (!hasAnnotation(javacNode, JacksonAnnotationType.JSON_PROPERTY2)) {
		createJsonPropertyForField(javacNode, annotationNode);
	}
```

Comment (Rawi01) [reply src/core/lombok/javac/handlers/HandleJacksonized.java]: I agree that `continue` is more readable.

Your proposal would add `@JsonProperty` even if the field was already annotated with `@JsonIgnore`.

Comment (ralemanc) [reply src/core/lombok/javac/handlers/HandleJacksonized.java]: I also agree with the use of `continue`.

Indeed: 
* If the field is `transient` and annotated with `@JsonProperty`, `@JsonIgnore` will be added.
* If the field is not `transient` and annotated with `@JsonIgnore`, `@JsonProperty` will be added.

**Additional context**
The PR where it was introduced, in case it helps provide some context: https://github.com/projectlombok/lombok/pull/3945

**Comment by ralemanc** [comment]
As a side comment, does it make sense to add `@JsonIgnore` if the field is annotated with `@JsonFormat`?

**Additional context**
https://github.com/FasterXML/jackson-databind/issues/3357

File: src/core/lombok/javac/handlers/HandleJacksonized.java (hunk 1 above)
Comment (nealeu) [reply src/core/lombok/javac/handlers/HandleJacksonized.java]: > I agree that `continue` is more readable.
> 
> Your proposal would add `@JsonProperty` even if the field was already annotated with `@JsonIgnore`.

Ah yes.  Good point.

And how long before Github add a workflow that comes back with "your suggestion caused the following tests to fail", which I hope would have been the case.

Comment (ralemanc) [reply src/core/lombok/javac/handlers/HandleJacksonized.java]: Updated the code using `continue.` 

There is a warning in the IDE: `'continue' is unnecessary as the last statement in a loop`.

Comment (nealeu) [reply src/core/lombok/javac/handlers/HandleJacksonized.java]: Yes. That's because you can remove the `else` that follows when it's expressed that way.

Comment (ralemanc) [reply src/core/lombok/javac/handlers/HandleJacksonized.java]: > Yes. That's because you can remove the `else` that follows when it's expressed that way.

Ups ;)  Right. Code updated.

**Comment by rzwitserloot** [comment]
@ralemanc We've reviewed this PR and it's accepted, but we can't merge this PR until you add your name to the AUTHORS file as part of this PR (for copyright/legal reasons).

**Comment by ralemanc** [comment]
> @ralemanc We've reviewed this PR and it's accepted, but we can't merge this PR until you add your name to the AUTHORS file as part of this PR (for copyright/legal reasons).

@rzwitserloot Done. Thanks!
